### ISSUE TITLE
コードレビューの指摘事項を改善する

### ISSUE THREAD

**Issue by hokkey** [hokkey/qiita-widget-js#1]
レビュアー: @i78s

- QiitaWidgetにwhileループの処理を書くべきではなく、他へ分けるべき
- fetchOnceが副作用とbooleanの戻り値の両方の仕事を持っているのが良くない
- parseDataListは引数をとるようにするべき
- パラメータを信用しなさすぎるのも良くない
  - https://slack-redir.net/link?url=https%3A%2F%2Fspeakerdeck.com%2Ftwada%2Fphp-conference-2016
- QiitaPresenter内で配列をshuffleするべきではなく、データの加工を他へ分けるべき
- CachedApiのネーミングが良くない
- キャッシュ機能にaxiosのadapterを使うべき
  - https://github.com/RasCarlito/axios-cache-adapter
- 方針にもよるが、HTMLテンプレートや、配列のシャッフルは自前でななくlodash使ってもいいかも

**Comment by i78s** [comment]
> QiitaWidgetにwhileループの処理を書くべきではなく、他へ分けるべき

正確には `/api/QiitaUserItem.getAll()` みたいにAPIとの通信 + 全件取る処理 を外に出すべき

> parseDataListは引数をとるようにするべき

stateに依存するので配列を引数で取り整形したデータ（配列）を返すとテスタブル

> QiitaPresenter内で配列をshuffleするべきではなく、データの加工を他へ分けるべき

責務をなるべく小さく切り分ける。QiitaPresenterは値を受け取りviewを作ることだけに徹する

> CachedApiのネーミングが良くない

* 名前から何をするのか想像しずらい `/api/QiitaUserItem` とかならqiitaのユーザーの投稿関連のAPIを叩くもの とわかる
* axiosのadapterを使えばcache処理も外に出る -> CachedApiではなくなる

**Comment by hokkey** [comment]
@i78s 土日にnpmへの公開へ向けた整理を行いつつ、指摘事項を修正しました。

レビュー時点：
https://github.com/hokkey/qiita-widget-js/tree/0.0.3/src

npmリリース版：
https://github.com/hokkey/qiita-widget-js/tree/0.2.1/lib

### 改善1：キャッシュ機能の改善

> CachedApiのネーミングが良くない
> キャッシュ機能にaxiosのadapterを使うべき

キャッシュ機能をaxios側で賄うため、旧CachedResponseは廃止。旧CachedApiを[Api](https://github.com/hokkey/qiita-widget-js/blob/0.2.1/lib/Api.ts)に改称しました。

(axios-cache-adapterが[localforage](https://github.com/localForage/localForage)への依存があり、依存ライブラリが1つ増えちゃいました……。でもこのライブラリ良さそうですね！)

### 改善2：肥大化したQiitaWidgetとQiitaPresenterの機能を新クラスへ分離

> QiitaPresenter内で配列をshuffleするべきではなく、データの加工を他へ分けるべき

旧QiitaWidgetの処理の一部と、旧QiitaPresenterの行っていたデータ操作的な処理を新たに[QiitaItemsクラス](https://github.com/hokkey/qiita-widget-js/blob/0.2.1/lib/QiitaItems.ts)としてまとめなおしました。QiitaItemsの責任範囲はのレスポンスデータのリクエストと、プレゼンター用のデータの整形／出力です。

> QiitaWidgetにwhileループの処理を書くべきではなく、他へ分けるべき

旧QiitaWidgetと旧CachedApiParamCreatorの機能を統合した[QiitaItemsApi](https://github.com/hokkey/qiita-widget-js/blob/0.2.1/lib/QiitaItemsApi.ts)を新たに作成しました。責任範囲はQiitaItemsへ渡すためのデータの取得です。

> fetchOnceが副作用とbooleanの戻り値の両方の仕事を持っているのが良くない

こちらは、continue/breakの必要性を判断する機能と、レスポンスをプロパティに追加する機能にきっちり分けました。
https://github.com/hokkey/qiita-widget-js/blob/0.2.1/lib/QiitaItemsApi.ts#L71

### 改善3：過剰な防衛の削除

> パラメータを信用しなさすぎるのも良くない

型の検査は、iframeの機能でdivからパラメータを取るところだけに抑えました。最大値／最小値の検査などは引き続き実装されています。

### 未改善箇所

> 方針にもよるが、HTMLテンプレートや、配列のシャッフルは自前でななくlodash使ってもいいかも

こちらは引き続き自前実装のままです。

### その他

QiitaWidgetの初期化後にiframeの高さを調整したくなり[window.postMessage](https://github.com/hokkey/qiita-widget-js/blob/0.2.1/lib/iframe/makeIframeContent.ts#L27)というものを初めて使ってみました。異なるwindow間で通信する仕組みがあるなんて知りませんでした…!

**Comment by hokkey** [comment]
今回のケースをまとめた記事を投稿しました。
https://qiita.com/y_hokkey/items/055e335b9d6d6f77c7ad
(ホットエントリにも乗りました!)

これでクローズします。レビューしていただきありがとうございました!
